#! /bin/sh
#
# Test suite for libtap functionality.
#
# Written by Russ Allbery <eagle@eyrie.org>
# Copyright 2009, 2012, 2013 Russ Allbery <eagle@eyrie.org>
# Copyright 2008, 2013
#     The Board of Trustees of the Leland Stanford Junior University
#
# See LICENSE for licensing terms.

echo "1..1"
echo "ok 1 no tests"
