#!/bin/sh
set -e
pwd
if [ "" = "`which runtests`" ]; then
echo "installing prerequisites"
cd c-tap-harness && ./autogen && ./configure --prefix $OLDPWD/opt && make install
cd ..
export PATH=$PATH:$PWD/opt/bin
fi

echo "building project"
make check
